version: "3"

services:
    iot_1:
        container_name: server-IoT-1
        restart: always
        # build: .
        image: blake0101/iot-plantas-lite
        ports: 
            - "4050:4050"
        environment:
            - TZ=America/La_Paz
            - PORT=4050
        # volumes:
        #     - .:/usr/src/app
    iot_2:
        container_name: server-IoT-2
        restart: always
        # build: .
        image: blake0101/iot-plantas-lite
        ports: 
            - "4060:4060"
        environment:
            - TZ=America/La_Paz
            - PORT=4060